"""Initial migration

Revision ID: 95f143451c15
Revises:
Create Date: 2026-02-25 21:33:13.231538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95f143451c15'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('role', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('bookings',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('user_id', sa.Uuid(), nullable=False),
                    sa.Column('room_number', sa.String(), nullable=False),
                    sa.Column('original_checkout', sa.DateTime(), nullable=False),
                    sa.Column('status', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('extension_requests',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('booking_id', sa.Uuid(), nullable=False),
                    sa.Column('requested_time', sa.DateTime(), nullable=False),
                    sa.Column('status', sa.String(), nullable=True),
                    sa.Column('price_quote', sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extension_requests')
    op.drop_table('bookings')
    op.drop_table('users')
    # ### end Alembic commands ###
