"""Add foreign keys

Revision ID: f5feca2f26d7
Revises: fffa14f2bb5c
Create Date: 2026-02-27 21:23:25.443947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5feca2f26d7'
down_revision: Union[str, None] = 'fffa14f2bb5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_bookings_user_id_users', 'bookings', 'users', ['user_id'], ['id'])
    op.create_foreign_key('fk_extension_requests_booking_id_bookings', 'extension_requests', 'bookings', ['booking_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_extension_requests_booking_id_bookings', 'extension_requests', type_='foreignkey')
    op.drop_constraint('fk_bookings_user_id_users', 'bookings', type_='foreignkey')
    # ### end Alembic commands ###
